CREATE TABLE company  (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(128) NOT NULL UNIQUE
    );

CREATE TABLE employee (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(128) NOT NULL
);